### ISSUE TITLE
[1.20.1] Errored Texture and Missing Door Variants

### ISSUE THREAD

**Issue by RileyCasper** [DragN0007/Thats-Just-Peachy#1]
Trapdoors have a strange texture glitch. Is only apparent in 1.20.1
[I'll reply with a picture if I remember to take one. I wanted to just jot this down before I forgot.]

1.20.1 is also missing Cherry Door(Trapdoor) and Mangrove Door(Trapdoor) <3

**Comment by DragN0007** [comment]
Thanks for the issue input! I'll take a look and get out a fix for it as soon as possible.

I completely forgot about the Cherry, Mangrove and Bamboo variants for 1.19/ 1.20. I'll include that in the same patch. Whoops!

**Comment by DragN0007** [comment]
Just uploaded the 1.6 patch. Fixed loot table issues, added the Mangrove, Cherry, and Bamboo variants, and fixed the issue where you could look upon the matrix through a door / trapdoor ^^

Let me know how it goes whenever you can!
